### ISSUE TITLE
Max testing Monday integrations

### ISSUE THREAD

**Issue by maxstarkenburg** [gwu-libraries/git-sandbox#17]
Using this to test whether there are 1) difficulties related to repos within the gwu-libraries org, or 2) problems with tickets existing before a particular integration was set up with that repo on Monday.com (e.g. will it create a new item for the ticket as soon as I comment on it post-integration, and will pre-integration follow-up comments make it over to Monday?)

**Comment by maxstarkenburg** [comment]
Comment 1 (or is it 2?). Edited to see if original or edit comes through.

**Comment by maxstarkenburg** [comment]
Comment 2 (or is it 3?)

**Comment by qbaron** [comment]
Comment 3 (or 4?) from someone other than Max.

**Comment by qbaron** [comment]
Also wondering what happens if I tag @maxstarkenburg

**Comment by maxstarkenburg** [comment]
Commented made after "new GitHub issue creates new Monday item" integration has been made, but before "new comment on GitHub issues creates new update to synced Monday item" integration was made.

**Comment by maxstarkenburg** [comment]
Comment post-"new GitHub comment creates Monday update" integration.

**Comment by maxstarkenburg** [comment]
Closing this (moved testing to a different repo I was an admin of).
